### ISSUE TITLE
Crash with Simply Jetpacks - 2.2.18.1

### ISSUE THREAD

**Issue by reddvilzz** [TeamDman/PlusTiC#29]
Using PlusTic 8.0.2 Alpha
Simply Jetpacks - 2.2.18.1

Crashes when equipping Construct Armory with the Jetpack Modifier when trying to fly/using the jetpack or even moving on foot when the armor is equipped. @TeamDman 

[crash-2021-02-02_14.35.21-client.txt](https://github.com/TeamDman/PlusTiC/files/5909428/crash-2021-02-02_14.35.21-client.txt)

**Comment by TeamDman** [comment]
Hopefully fixed in latest
https://www.curseforge.com/minecraft/mc-mods/plusticminusbad/files/3645594
If not, can reopen
