### ISSUE TITLE
Make a new release to make it compatible with Simply Jetpacks

### ISSUE THREAD

**Issue by Pelotrio** [TeamDman/PlusTiC#32]
The game currently crashes with the newest version of Simply Jetpacks 2. The commits to fix this are already there but there is no release on cursforge yet.

**Comment by TeamDman** [comment]
I think the builds were marked as alpha.
I've added another file marked as release
https://www.curseforge.com/minecraft/mc-mods/plusticminusbad/files/3319812

lmk if this crashes and I'll try again.

**Comment by Pelotrio** [comment]
Thank you very much @TeamDman. I will take a look at it as soon as I can.

**Comment by Pelotrio** [comment]
Booted up fine so far with no issues so it seems like its working. Thank you again @TeamDman.
