### ISSUE TITLE
Breaks when installed alongside Fossils and Archeology.

### ISSUE THREAD

**Issue by brisingraerowing** [TeamDman/PlusTiC#41]
[Crash Log](https://gist.github.com/brisingraerowing/7abf5f58be46e21e866f433fd05a04c3)

Happens during game launch.

**Comment by brisingraerowing** [comment]
Actually, this crashes without F&A as well. It seems something didn't remap correctly.

**Comment by TeamDman** [comment]
Please try latest build, sorry for the issues
https://www.curseforge.com/minecraft/mc-mods/plusticminusbad/files/3648592
