### ISSUE TITLE
Crash on stratup - NoClassDefFoundError

### ISSUE THREAD

**Issue by jkrumpholc** [TeamDman/PlusTiC#43]
PlusTiC version - 8.0.5
Minecraft version: 1.12.2
Forge Version: forge-14.23.5.2860
[crash-2022-02-15_08.48.01-client.txt](https://github.com/TeamDman/PlusTiC/files/8066911/crash-2022-02-15_08.48.01-client.txt)

**Comment by Breadabix** [comment]
Just found this as well, setting "Add Simply Jetpacks as ConArm modifiers" to false seems to fix it.
