### ISSUE TITLE
Issue with 8.0.5 with FTB Revolution

### ISSUE THREAD

**Issue by elaralara** [TeamDman/PlusTiC#46]
Mod instantly crashes when it tries to initialise in this curseforge modpack, attached is the crash report. 
[crash-2022-04-03_21.18.23-client.txt](https://github.com/TeamDman/PlusTiC/files/8405450/crash-2022-04-03_21.18.23-client.txt)

**Comment by TeamDman** [comment]
The modpack is using an older ver of SimplyJetpacks, from your crash:  
`| LCHI  | simplyjetpacks                    | 2.2.13.66                | SimplyJetpacks2-1.12.2-2.2.13.66.jar`
The new plustic ver expects a newer jetpacks build  
From a different crash log:  
`| LCHI  | simplyjetpacks                    | 1.12.2-2.2.20.0           | SimplyJetpacks2-1.12.2-2.2.20.0.jar `

Try updating the jetpacks or downgrading plustic

**Comment by elaralara** [comment]
thanks a ton, simply updating simplyjetpacks fixed the entire problem. glad to have full access to tconstruct on my server now this is great. kudos man

**Comment by TeamDman** [comment]
Glad to hear it worked 😅
