### ISSUE TITLE
[Suggestion] A change to the Hearts Trait.

### ISSUE THREAD

**Issue by SonicX8000** [TeamDman/PlusTiC#5]
Hearts Trait as it currently is... can get quite powerful depending on the tool's base damage & the damage bonus scaled based on the player's remaining health from max health and if one has a lot of health... the damage boost diminishes slower.

It's default damage boost if I recall is +70% if at full health, which is 0.7 which lowers depending on your remaining health from max health. I wonder if this boost could be lowered to 50% aka 0.5 & only apply the damage bonus if the player was at full health, for example...

If the Player was at 20/20 health, +50% damage bonus.
If the Player was at 100/100 health, +50% damage bonus.

If the Player was at 19/20 health, no damage bonus.
If the Player was at 99/100 health, no damage bonus.

-----

If the 'being at full health' is too much of a nerf. I suppose if you've above 80% health at least, you'll get the damage boost but if you drop below 80% health... no damage bonus. It could also be scalable if between 80% to 100% health. Like...

If the Player was at 20/20 health aka 100%, +50% damage bonus.
If the Player was at 18/20 health aka 90%, +25% damage bonus.
If the Player was at 16/20 health aka 80%, +0% damage bonus.

**Comment by TeamDman** [comment]
Might revisit if I end up creating a new mod for newer versions, but the mod is currently only in legacy support, so this request won't be able to be fielded for this mod.
