### ISSUE TITLE
modpack rejected cause of plustic name

### ISSUE THREAD

**Issue by TheNimbleNinja** [TeamDman/PlusTiC#7]
my modpack got rejected cause plustic was in the pack and the only plustic i have is yours

**Comment by DigitalData** [comment]
Not the mod dev, but it might help to know exactly how you include the file in your pack. A pack I've made has been approved with this mod included. I added it by specifically installing the latest version of this mod (xXx_MoreToolMats_xXx) within the Twitch launcher. It appears in the dependency list. 
Hopefully, that fixes the issue.

**Comment by TeamDman** [comment]
Indeed, the old PlusTiC was a separate project. If you had a drafted pack with that version, it makes sense that it got rejected since that mod was pulled from curseforge. 
Try again maybe with the this one
https://www.curseforge.com/minecraft/mc-mods/plusticminusbad
